### PR TITLE
Generator.{Interface, Object, Union}: Expose field for __typename

### PR DESCRIPTION
**Pull request by xtian**
[From the GraphQL spec][typename-introspection]:

> GraphQL supports type name introspection at any point within a query by the meta field __typename: String! when querying      against any Object, Interface, or Union.

This PR adds a `typename__` function to the generated modules for interfaces, objects, and unions, which allows the `__typename` field to be queried.

This might not be worth adding for objects and unions, but in the project I work on we have a couple cases where we render a list from an interface query and we use `__typename` to generate a class name for each row.

[typename-introspection]: https://github.com/facebook/graphql/blob/master/spec/Section%204%20--%20Introspection.md#type-name-introspection

### CODE REVIEW

**Comment by dillonkearns** [comment]
Hey @xtian, thanks for the PR. I set out with the goal to try to encapsulate as many low-level details as possible into higher-level, first-class Elm language constructs, and I would love to do the same for typenames. Right now you can get the type if you are using an Interface or a Union using the `on<Type>` functions. Like in this code from the StarWars example:

https://github.com/dillonkearns/graphqelm/blob/master/examples/src/Starwars.elm#L34-L36

https://github.com/dillonkearns/graphqelm/blob/master/examples/src/Starwars.elm#L65-L70

Not only is this more high-level than using the `__typename` field, but it is more typesafe. That is, let’s say that you renamed or removed the type `Droid` (that’s generally not a good practice but you’d still want the compiler to help you catch it). If you were using the `__typename` field directly here then your code that checks if `typename__` equals `”Droid”` would not let you know that this is no longer possible. Whereas with the `onDroid` function, that function would disappear and cause a compiler error.

I noticed that with the current setup you couldn’t easily get just the type with no parameters as a union. So I think it would be handy to have a `SelectionSet.succeed : value -> SelectionSet value typeLock` function. Then you could do something like:

```haskell
type HumanOrDroid
    = Human
    | Droid

hero : SelectionSet Character Swapi.Interface.Character
hero =
    Character.selection Character
        [ Character.onDroid (SelectionSet.succeed Droid)
        , Character.onHuman (SelectionSet.succeed Human)
        ]
-- ...
```

I’m not sure if you were aware of that functionality in the library or not? It needs to be documented better.

Do you have a specific use case you are trying to solve or that you are thinking about? I may be missing something here, but I think with the addtion of `SelectionSet.succeed` you can do everything you would want to do with the `typename__` but with Elm constructs rather than String equality checks. I would love to hear what you had in mind. Thanks!

**Comment by dillonkearns** [comment]
@xtian whoops, sorry I was responding to the content from the original issue in my email inbox, but I didn’t see that you had edited it to add more info about your use case.

> This might not be worth adding for objects and unions, but in the project I work on we have a couple cases where we render a list from an interface query and we use __typename to generate a class name for each row.

Do you think that the existing functionality, at least with `SelectionSet.succeed` added to the package, would allow you to achieve this? I believe it would, but correct me if I’m wrong. It would be great to hear your thoughts and whether you think that is still not sufficient or isn’t an elegant solution in your case. Thanks!

**Comment by dillonkearns** [comment]
Another thought, if there's a compelling use case for it, we could have interface and union modules include a union type like

```haskell
type TypeName 
    = Human
    | Droid
```

And include a SelectionSet for typename much like yours except that it would just Decode.map into the above union type rather than staying as a string.

The same would apply to Unions.

I think this would allow you to query for typename in a strongly typed way (rather than stringly typed), and would allow you to do exhaustive checks. In your case as you described it, this would be beneficial because it would ensure that you are not forgetting to register a type name (which with my approach in the previous approach you could forget a type).

Thoughts?

**Comment by xtian** [comment]
@dillonkearns I saw the `on<variant>` functions but I didn't really understand how to use them. Your example makes it clearer though - thanks!

I think you are right that `SelectionSet.succeed` would make it possible to solve our use-case. Will `SelectionSet.hardcoded` not work in this context?

As far as a `TypeName` union, I don't really have an opinion.

Let me know which direction you'd like to pursue and I can open another PR.

**Comment by dillonkearns** [comment]
Hey @xtian that’s true that `SelectionSet.hardcoded` would work in this case, I hadn’t considered that! It will be a little simpler if you have `SelectionSet.succeed`, though.

The difference would be something like:

```haskell
Character.onDroid (Swapi.Object.Droid.selection |> SelectionSet.hardcoded Droid)
```

Versus

```haskell
Character.onDroid (SelectionSet.succeed Droid)
```

Would you mind trying it out with the hardcoded workaround for now and letting me know how that feels?

That will give us a data point to discuss whether a TypeName union would be the best solution to this problem. I would love to hear your feedback on that experience, I think that’s the best way to consider design choices is by actually trying out code and iterating from the experience!

And I will definitely add `SelectionSet.succeed` when I’m back home in a week, but for now it seems like the hardcoded workaround probably isn’t to ugly to try out.

**Comment by dillonkearns** [comment]
@xtian I [added a `SelectionSet.succeed` function](http://package.elm-lang.org/packages/dillonkearns/graphqelm/10.2.0/Graphqelm-SelectionSet#succeed)! Just a convenience, but hopefully that helps. Hope this approach is working out nicely for you.

**Pull request closed without merging**
