### PR TITLE
Detect elm-format path

### PR DESCRIPTION
**Pull request by martimatix**
See issue https://github.com/dillonkearns/graphqelm/issues/10

### CODE REVIEW

**Comment by dillonkearns** [comment]
Awesome, thank you for fixing Mario! Somehow I didn't see this issue when I tested it, I thought a was using the globally installed version but I guess not.

**Comment by dillonkearns** [comment]
So it seems that it wasn't packaging up the elm-format executable... I was trying to wrap my brain around how it packaged that up earlier and I guess it actually doesn't. I was thinking I wonder if there could be some way to use `webpack` to import the code... but that may not work because I believe there's a fair amount of haskell code in the `elm-format` project.

This is a good stopgap, and I believe all the code that is generated is syntactically valid without running `elm-format` on it, but it would be good to add a check for that in CI. I'll work on that.

**Comment by martimatix** [comment]
@dillonkearns In the process of installing, uninstalling and updating various packages, I think funny things can happen with the node_modules folder.

Just tested 0.0.8 of graphqelm CLI and elm-format is working when it is installed globally and locally.

Luke Westby mentioned on the Elm Town podcast that he was able to get the Elm compiler written in Haskell to run in the browser for Ellie by compiling it using ghcjs. So anything's possible!

Happy new year and I hope you're pleased as I am about the progress of this project. 😄

**Comment by dillonkearns** [comment]
Thanks Mario, I am pleased and I can't wait to share this with the broader public once I finish my short-list! I just got the code-generation for Interfaces working, and Unions are the same concept so that won't take long. Your feedback and contributions have really helped improve the project, I can't thank you enough!

Actually, I would love to hear your thoughts on the API for interfaces. I opened an issue #14 if you've got a moment to take a look.

Happy New Year!

**Pull request merged**
